name: poetry CI

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.7

      - name: Install poetry
        uses: Gr1N/setup-poetry@v4
        with:
          poetry-version: 1.1.4

      - name: Install bwa/samtools
        run: |
          sudo apt-get install -y bwa samtools

      - name: Install dependencies
        run: |
          poetry install

      - name: Test
        run: |
          make -j4 test