name: poetry CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    name: Poetry build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.7

      - name: Install poetry
        uses: Gr1N/setup-poetry@v4
        with:
          poetry-version: 1.1.4


      - name: Install dependencies
        run: |
          poetry install
      - name: Test
        run: |
          make test